# Generated by Django 6.0 on 2025-12-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
