# Generated by Django 5.1.2 on 2025-12-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='seen',
        ),
    ]
